import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'preferences_service.dart';

/// Supported languages in the app
enum AppLanguage { english, spanish, french, german, arabic, chinese }

/// Language configuration with locale and display name
class LanguageConfig {
  final AppLanguage language;
  final Locale locale;
  final String displayName;
  final bool isRTL;

  const LanguageConfig({
    required this.language,
    required this.locale,
    required this.displayName,
    this.isRTL = false,
  });
}

/// Service to manage app language state with persistence
class LanguageService extends ChangeNotifier {
  final PreferencesService _prefs = PreferencesService();

  AppLanguage _language = AppLanguage.english;
  bool _isInitialized = false;

  // Language configurations - centralized for easy maintenance
  static const Map<AppLanguage, LanguageConfig> _languageConfigs = {
    AppLanguage.english: LanguageConfig(
      language: AppLanguage.english,
      locale: Locale('en'),
      displayName: 'English',
    ),
    AppLanguage.spanish: LanguageConfig(
      language: AppLanguage.spanish,
      locale: Locale('es'),
      displayName: 'Spanish',
    ),
    AppLanguage.french: LanguageConfig(
      language: AppLanguage.french,
      locale: Locale('fr'),
      displayName: 'French',
    ),
    AppLanguage.german: LanguageConfig(
      language: AppLanguage.german,
      locale: Locale('de'),
      displayName: 'German',
    ),
    AppLanguage.arabic: LanguageConfig(
      language: AppLanguage.arabic,
      locale: Locale('ar'),
      displayName: 'Arabic',
      isRTL: true,
    ),
    AppLanguage.chinese: LanguageConfig(
      language: AppLanguage.chinese,
      locale: Locale('zh'),
      displayName: 'Chinese',
    ),
  };

  AppLanguage get language => _language;
  bool get isInitialized => _isInitialized;

  /// Get current language config
  LanguageConfig get currentConfig => _languageConfigs[_language]!;

  /// Get the locale for the current language
  Locale get locale => currentConfig.locale;

  /// Check if current language is RTL
  bool get isRTL => currentConfig.isRTL;

  /// Initialize language from stored preference
  Future<void> initialize() async {
    if (_isInitialized) return;

    final storedLanguage = await _prefs.language;

    if (storedLanguage != null) {
      _language = AppLanguage.values.firstWhere(
        (e) => e.name == storedLanguage,
        orElse: () => AppLanguage.english,
      );
    }

    _isInitialized = true;
    notifyListeners();
  }

  /// Set language and persist
  Future<void> setLanguage(AppLanguage lang) async {
    if (_language == lang) return;

    _language = lang;
    notifyListeners();

    await _prefs.setLanguage(lang.name);
  }

  /// Set language by display name
  Future<void> setLanguageByName(String name) async {
    final config = _languageConfigs.values.firstWhere(
      (c) => c.displayName == name,
      orElse: () => _languageConfigs[AppLanguage.english]!,
    );
    await setLanguage(config.language);
  }

  /// Get language display name
  String getLanguageDisplayName() => currentConfig.displayName;

  /// Get translated string
  String translate(String key) {
    return _translations[_language]?[key] ??
           _translations[AppLanguage.english]![key] ??
           key;
  }

  /// Translations map - organized by language
  static final Map<AppLanguage, Map<String, String>> _translations = {
    AppLanguage.english: _englishTranslations,
    AppLanguage.spanish: _spanishTranslations,
    AppLanguage.french: _frenchTranslations,
    AppLanguage.german: _germanTranslations,
    AppLanguage.arabic: _arabicTranslations,
    AppLanguage.chinese: _chineseTranslations,
  };
}

// English translations (base language)
const Map<String, String> _englishTranslations = {
  // App
  'app_name': 'AssetCapture',
  'quality_inspection': 'Quality Inspection',
  'loading': 'Loading...',
  'version': 'Version',

  // Auth
  'sign_in_with_google': 'Sign in with Google',
  'secure_auth': 'Secure authentication with Google',
  'signing_in': 'Signing in...',
  'sign_in_cancelled': 'Sign-in was cancelled or failed',

  // Tabs & Navigation
  'details': 'Details',
  'scanner': 'Scanner',

  // Main Screen
  'device_info': 'Device Information',
  'completion_status': 'Completion Status',
  'photos': 'Photos',
  'no_photos': 'No photos yet',
  'tap_to_add': 'Tap the camera button to add photos',
  'add_photo': 'Add Photo',
  'add_photos': 'Add Photos',
  'take_photo': 'Take Photo',
  'choose_gallery': 'Choose from Gallery',
  'cancel': 'Cancel',
  'close': 'Close',
  'delete': 'Delete',
  'remove': 'Remove',
  'save': 'SAVE',
  'view': 'View',

  // Scanner Section
  'scanned': 'Scanned',
  'start_scanning': 'Start Scanning',
  'scan_again': 'Scan Again',
  'barcode_id': 'Barcode ID',
  'not_scanned': 'Not scanned',
  'barcode_copied': 'Barcode copied to clipboard',

  // Description Section
  'asset_description': 'Asset Description',
  'optional': 'Optional',
  'description': 'Description',
  'description_hint': 'Describe the asset condition, any defects, scratches, or special notes...',
  'characters': 'characters',
  'empty': 'Empty',
  'added': 'Added',

  // Upload
  'add_to_upload_queue': 'ADD TO UPLOAD QUEUE',
  'upload_queued': 'Upload queued! You can continue scanning.',
  'failed_queue_upload': 'Failed to queue upload',
  'scan_barcode_first': 'Please scan a barcode first before uploading',
  'take_photo_first': 'Please take at least 1 photo before uploading',
  'enter_barcode_and_photo': 'Please enter a barcode and take at least 1 photo',
  'uploading': 'Uploading',
  'n_uploads_in_queue': 'upload(s) in queue',
  'more_in_queue': 'more in queue',
  'photos_saved_go_details': 'photo(s) saved. Go to Details tab to upload.',
  'upload_complete_opening_link': 'Upload complete! Opening shareable link...',
  'could_not_open_browser': 'Could not open browser',
  'failed_open_link': 'Failed to open link',
  'failed_open_scanner': 'Failed to open scanner. Please try again.',
  'failed_open_camera': 'Failed to open camera. Please try again.',

  // Delete Photo Dialog
  'delete_photo': 'Delete Photo',
  'delete_photo_confirm': 'Are you sure you want to delete this photo?',

  // Upload Success
  'upload_successful': 'Upload Successful!',
  'verify_data': 'Please verify the data below before submitting to warehouse:',
  'barcode_number': 'Barcode Number',
  'photos_uploaded': 'Photos Uploaded',
  'barcode_image': 'Barcode Image',
  'included': 'Included',
  'not_available': 'Not available',
  'no_description': 'No description',
  'drive_folder': 'Google Drive Folder:',
  'submit_to_warehouse': 'Submit to Warehouse',
  'opening_warehouse': 'Opening warehouse form...',

  // Logout
  'logout_confirm': 'Are you sure you want to logout?',

  // Photo Preview
  'photo_preview': 'Photo Preview',

  // Upload Queue Screen
  'upload_queue': 'Upload Queue',
  'active': 'active',
  'completed': 'completed',
  'failed': 'failed',
  'clear_completed': 'Clear completed',
  'no_uploads': 'No uploads in queue',
  'scanned_assets_appear': 'Scanned assets will appear here',
  'waiting': 'Waiting',
  'just_now': 'Just now',
  'link_copied': 'Link copied to clipboard',
  'remove_upload': 'Remove Upload',
  'remove_upload_confirm': 'Remove from the queue?',
  'copy_link': 'Copy link',

  // Device Info Fields
  'brand': 'Brand',
  'model': 'Model',
  'serial_number': 'Serial Number',
  'imei': 'IMEI',
  'storage': 'Storage',
  'condition': 'Condition',
  'uploaded': 'uploaded',

  // Completion Status
  'photos_taken': 'Photos Taken',
  'device_scanned': 'Device Scanned',
  'info_verified': 'Info Verified',
  'complete': 'Complete',
  'incomplete': 'Incomplete',

  // Settings
  'settings': 'Settings',
  'general': 'General',
  'language': 'Language',
  'select_language': 'Select your preferred language',
  'preferences': 'Preferences',
  'theme': 'Theme',
  'customize_appearance': 'Customize app appearance',
  'select_theme': 'Select Theme',
  'notifications': 'Notifications',
  'receive_updates': 'Receive upload status notifications',
  'auto_upload': 'Auto Upload',
  'auto_upload_subtitle': 'Automatically queue upload when barcode and photos are ready',
  'auto_sync': 'Automatically sync photos to Drive',
  'legal': 'Legal',
  'terms_of_service': 'Terms of Service',
  'privacy_policy': 'Privacy Policy',
  'support': 'Support',
  'report_problem': 'Report a Problem',
  'rate_app': 'Rate the App',
  'about': 'About',
  'app_info': 'App Info',
  'version_info': 'Version and app information',
  'app_description': 'A professional quality inspection app for streamlined asset documentation.',

  // Theme
  'dark': 'Dark',
  'light': 'Light',
  'system': 'System',

  // Drive Connection
  'google_drive': 'Google Drive',
  'connect_drive_desc': 'Connect your Google Drive to securely\nstore and sync your photos',
  'connect_to_drive': 'Connect to Google Drive',
  'connecting': 'Connecting to Google Drive...',
  'connected': 'Connected Successfully!',
  'connection_failed': 'Connection Failed',
  'continue_to_app': 'Continue to App',
  'retry': 'Retry Connection',
  'auth_expired': 'Authentication expired. Please sign in again.',

  // Onboarding
  'scan_qr': 'Scan QR Codes',
  'scan_qr_desc': 'Quickly scan QR codes with your camera and get instant results.',
  'scan_barcodes': 'Scan Barcodes',
  'scan_barcodes_desc': 'Support for all major barcode formats including EAN, UPC, and Code 128.',
  'save_export': 'Save & Export',
  'save_export_desc': 'Save your scans and export them directly to Google Drive.',
  'skip': 'Skip',
  'next': 'Next',
  'get_started': 'Get Started',
  'welcome_title': 'Welcome to\nInspector',
  'welcome_subtitle': 'The fastest way to scan, inspect, and document\nyour assets with professional quality',
  'quick_scanning': 'Quick barcode scanning',
  'multi_angle_capture': 'Multi-angle photo capture',
  'secure_cloud_storage': 'Secure cloud storage',
  'instant_recognition': 'Instant Barcode\nRecognition',
  'recognition_desc': 'Simply point your camera at any barcode and get\ninstant results. Supports all major formats including\nEAN, UPC, and QR codes',
  'scan_speed': 'Scan Speed',
  'accuracy': 'Accuracy',
  'formats': 'Formats',
  'document_upload': 'Document &\nUpload Instantly',
  'document_upload_desc': 'Capture multiple photos from different angles and\nautomatically sync them to the cloud. All data is\nencrypted and secure',
  'upload_5_photos': 'Upload up to 5 photos per asset',
  'auto_sync_cloud': 'Auto-sync to cloud storage',
  'encryption': 'End-to-end encryption',
  'swipe_continue': 'or swipe to continue',

  // Drawer
  'home': 'Home',
  'scan_history': 'Scan History',
  'cloud_backup': 'Cloud Backup',
  'logout': 'Logout',
  'Profile': 'Profile',
  'View your profile': 'View your profile',
  'App preferences': 'App preferences',
  'Get help': 'Get help',

  // About
  'company': 'Company',
  'contact': 'Contact',
  'website': 'Website',
  'all_rights_reserved': 'All rights reserved.',

  // Camera
  'no_cameras': 'No cameras available on this device',
  'camera_init_failed': 'Failed to initialize camera. Please try again.',
  'capture_failed': 'Failed to capture photo. Try again.',
  'starting_camera': 'Starting camera...',
  'camera_not_available': 'Camera not available',
  'remaining_photos': 'photo(s) remaining',
  'max_photos_reached': 'Maximum photos reached',
  'retry_button': 'Retry',

  // Widget-specific
  'camera': 'Camera',
  'barcode_scanner': 'Barcode Scanner',
  'bcn_number': 'BCN NUMBER',
  'copy_bcn': 'Copy BCN',
  'barcode_captured': 'Barcode Captured',
  'scan_new_barcode': 'Scan New Barcode',
  'device_description': 'Device Description',
  'upload_to_drive': 'UPLOAD TO DRIVE',
};

// Spanish translations
const Map<String, String> _spanishTranslations = {
  'app_name': 'AssetCapture',
  'quality_inspection': 'Inspección de Calidad',
  'loading': 'Cargando...',
  'version': 'Versión',
  'sign_in_with_google': 'Iniciar sesión con Google',
  'secure_auth': 'Autenticación segura con Google',
  'signing_in': 'Iniciando sesión...',
  'sign_in_cancelled': 'El inicio de sesión fue cancelado o falló',
  'details': 'Detalles',
  'scanner': 'Escáner',
  'device_info': 'Información del Dispositivo',
  'completion_status': 'Estado de Completado',
  'photos': 'Fotos',
  'no_photos': 'Sin fotos aún',
  'tap_to_add': 'Toca el botón de cámara para agregar fotos',
  'add_photo': 'Agregar Foto',
  'add_photos': 'Agregar Fotos',
  'take_photo': 'Tomar Foto',
  'choose_gallery': 'Elegir de Galería',
  'cancel': 'Cancelar',
  'close': 'Cerrar',
  'delete': 'Eliminar',
  'remove': 'Quitar',
  'save': 'GUARDAR',
  'view': 'Ver',
  'scanned': 'Escaneado',
  'start_scanning': 'Iniciar Escaneo',
  'scan_again': 'Escanear de Nuevo',
  'barcode_id': 'ID de Código de Barras',
  'not_scanned': 'No escaneado',
  'barcode_copied': 'Código de barras copiado al portapapeles',
  'asset_description': 'Descripción del Activo',
  'optional': 'Opcional',
  'description': 'Descripción',
  'description_hint': 'Describe el estado del activo, defectos, rasguños o notas especiales...',
  'characters': 'caracteres',
  'empty': 'Vacío',
  'added': 'Agregado',
  'add_to_upload_queue': 'AGREGAR A COLA DE CARGA',
  'upload_queued': '¡Carga en cola! Puedes continuar escaneando.',
  'failed_queue_upload': 'Error al poner en cola la carga',
  'scan_barcode_first': 'Escanea un código de barras antes de cargar',
  'take_photo_first': 'Toma al menos 1 foto antes de cargar',
  'enter_barcode_and_photo': 'Ingresa un código de barras y toma al menos 1 foto',
  'uploading': 'Cargando',
  'n_uploads_in_queue': 'carga(s) en cola',
  'more_in_queue': 'más en cola',
  'photos_saved_go_details': 'foto(s) guardada(s). Ve a la pestaña Detalles para cargar.',
  'upload_complete_opening_link': '¡Carga completa! Abriendo enlace compartible...',
  'could_not_open_browser': 'No se pudo abrir el navegador',
  'failed_open_link': 'Error al abrir el enlace',
  'failed_open_scanner': 'Error al abrir el escáner. Inténtalo de nuevo.',
  'failed_open_camera': 'Error al abrir la cámara. Inténtalo de nuevo.',
  'delete_photo': 'Eliminar Foto',
  'delete_photo_confirm': '¿Estás seguro de que deseas eliminar esta foto?',
  'upload_successful': '¡Carga Exitosa!',
  'verify_data': 'Verifica los datos antes de enviar al almacén:',
  'barcode_number': 'Número de Código de Barras',
  'photos_uploaded': 'Fotos Cargadas',
  'barcode_image': 'Imagen del Código de Barras',
  'included': 'Incluida',
  'not_available': 'No disponible',
  'no_description': 'Sin descripción',
  'drive_folder': 'Carpeta de Google Drive:',
  'submit_to_warehouse': 'Enviar al Almacén',
  'opening_warehouse': 'Abriendo formulario de almacén...',
  'logout_confirm': '¿Estás seguro de que deseas cerrar sesión?',
  'photo_preview': 'Vista Previa de Foto',
  'upload_queue': 'Cola de Carga',
  'active': 'activa(s)',
  'completed': 'completada(s)',
  'failed': 'fallida(s)',
  'clear_completed': 'Limpiar completadas',
  'no_uploads': 'No hay cargas en cola',
  'scanned_assets_appear': 'Los activos escaneados aparecerán aquí',
  'waiting': 'En Espera',
  'just_now': 'Ahora mismo',
  'link_copied': 'Enlace copiado al portapapeles',
  'remove_upload': 'Quitar Carga',
  'remove_upload_confirm': '¿Quitar de la cola?',
  'copy_link': 'Copiar enlace',
  'brand': 'Marca',
  'model': 'Modelo',
  'serial_number': 'Número de Serie',
  'imei': 'IMEI',
  'storage': 'Almacenamiento',
  'condition': 'Condición',
  'uploaded': 'cargada(s)',
  'photos_taken': 'Fotos Tomadas',
  'device_scanned': 'Dispositivo Escaneado',
  'info_verified': 'Info Verificada',
  'complete': 'Completo',
  'incomplete': 'Incompleto',
  'settings': 'Configuración',
  'general': 'General',
  'language': 'Idioma',
  'select_language': 'Selecciona tu idioma preferido',
  'preferences': 'Preferencias',
  'theme': 'Tema',
  'customize_appearance': 'Personaliza la apariencia',
  'select_theme': 'Seleccionar Tema',
  'notifications': 'Notificaciones',
  'receive_updates': 'Recibir notificaciones de estado de carga',
  'auto_upload': 'Carga Automática',
  'auto_upload_subtitle': 'Cargar automáticamente cuando código y fotos estén listos',
  'auto_sync': 'Sincronizar fotos automáticamente',
  'legal': 'Legal',
  'terms_of_service': 'Términos de Servicio',
  'privacy_policy': 'Política de Privacidad',
  'support': 'Soporte',
  'report_problem': 'Reportar un Problema',
  'rate_app': 'Calificar la App',
  'about': 'Acerca de',
  'app_info': 'Info de la App',
  'version_info': 'Versión e información de la app',
  'app_description': 'Una app profesional de inspección de calidad para documentación de activos.',
  'dark': 'Oscuro',
  'light': 'Claro',
  'system': 'Sistema',
  'google_drive': 'Google Drive',
  'connect_drive_desc': 'Conecta tu Google Drive para almacenar\ny sincronizar tus fotos de forma segura',
  'connect_to_drive': 'Conectar a Google Drive',
  'connecting': 'Conectando a Google Drive...',
  'connected': '¡Conectado Exitosamente!',
  'connection_failed': 'Conexión Fallida',
  'continue_to_app': 'Continuar a la App',
  'retry': 'Reintentar Conexión',
  'auth_expired': 'Autenticación expirada. Inicia sesión de nuevo.',
  'scan_qr': 'Escanear Códigos QR',
  'scan_qr_desc': 'Escanea códigos QR rápidamente con tu cámara.',
  'scan_barcodes': 'Escanear Códigos de Barras',
  'scan_barcodes_desc': 'Soporte para todos los formatos principales.',
  'save_export': 'Guardar y Exportar',
  'save_export_desc': 'Guarda tus escaneos y expórtalos a Google Drive.',
  'skip': 'Omitir',
  'next': 'Siguiente',
  'get_started': 'Comenzar',
  'welcome_title': 'Bienvenido a\nInspector',
  'welcome_subtitle': 'La forma más rápida de escanear, inspeccionar y documentar\ntus activos con calidad profesional',
  'quick_scanning': 'Escaneo rápido de códigos',
  'multi_angle_capture': 'Captura fotográfica multi-ángulo',
  'secure_cloud_storage': 'Almacenamiento seguro en la nube',
  'instant_recognition': 'Reconocimiento\nInstantáneo de Códigos',
  'recognition_desc': 'Apunta tu cámara a cualquier código de barras y obtén\nresultados instantáneos. Soporta todos los formatos principales\nincluyendo EAN, UPC y códigos QR',
  'scan_speed': 'Velocidad',
  'accuracy': 'Precisión',
  'formats': 'Formatos',
  'document_upload': 'Documenta y\nCarga al Instante',
  'document_upload_desc': 'Captura múltiples fotos desde diferentes ángulos y\nsincroniza automáticamente en la nube. Todos los datos\nestán encriptados y seguros',
  'upload_5_photos': 'Carga hasta 5 fotos por activo',
  'auto_sync_cloud': 'Sincronización automática en la nube',
  'encryption': 'Encriptación de extremo a extremo',
  'swipe_continue': 'o desliza para continuar',
  'home': 'Inicio',
  'scan_history': 'Historial de Escaneos',
  'cloud_backup': 'Respaldo en la Nube',
  'logout': 'Cerrar Sesión',
  'Profile': 'Perfil',
  'View your profile': 'Ver tu perfil',
  'App preferences': 'Preferencias de la app',
  'Get help': 'Obtener ayuda',
  'company': 'Empresa',
  'contact': 'Contacto',
  'website': 'Sitio Web',
  'all_rights_reserved': 'Todos los derechos reservados.',
  'no_cameras': 'No hay cámaras disponibles en este dispositivo',
  'camera_init_failed': 'Error al inicializar la cámara. Inténtalo de nuevo.',
  'capture_failed': 'Error al capturar foto. Inténtalo de nuevo.',
  'starting_camera': 'Iniciando cámara...',
  'camera_not_available': 'Cámara no disponible',
  'remaining_photos': 'foto(s) restante(s)',
  'max_photos_reached': 'Máximo de fotos alcanzado',
  'retry_button': 'Reintentar',

  // Widget-specific
  'camera': 'Cámara',
  'barcode_scanner': 'Escáner de Códigos',
  'bcn_number': 'NÚMERO BCN',
  'copy_bcn': 'Copiar BCN',
  'barcode_captured': 'Código Capturado',
  'scan_new_barcode': 'Escanear Nuevo Código',
  'device_description': 'Descripción del Dispositivo',
  'upload_to_drive': 'CARGAR A DRIVE',
};

// French translations
const Map<String, String> _frenchTranslations = {
  'app_name': 'AssetCapture',
  'quality_inspection': 'Inspection Qualité',
  'loading': 'Chargement...',
  'version': 'Version',
  'sign_in_with_google': 'Se connecter avec Google',
  'secure_auth': 'Authentification sécurisée avec Google',
  'signing_in': 'Connexion en cours...',
  'sign_in_cancelled': 'La connexion a été annulée ou a échoué',
  'details': 'Détails',
  'scanner': 'Scanner',
  'device_info': 'Informations de l\'Appareil',
  'completion_status': 'État d\'Achèvement',
  'photos': 'Photos',
  'no_photos': 'Pas encore de photos',
  'tap_to_add': 'Appuyez sur le bouton caméra pour ajouter des photos',
  'add_photo': 'Ajouter Photo',
  'add_photos': 'Ajouter Photos',
  'take_photo': 'Prendre Photo',
  'choose_gallery': 'Choisir dans la Galerie',
  'cancel': 'Annuler',
  'close': 'Fermer',
  'delete': 'Supprimer',
  'remove': 'Retirer',
  'save': 'ENREGISTRER',
  'view': 'Voir',
  'scanned': 'Scanné',
  'start_scanning': 'Commencer le Scan',
  'scan_again': 'Scanner à Nouveau',
  'barcode_id': 'ID Code-barres',
  'not_scanned': 'Non scanné',
  'barcode_copied': 'Code-barres copié dans le presse-papiers',
  'asset_description': 'Description de l\'Actif',
  'optional': 'Facultatif',
  'description': 'Description',
  'description_hint': 'Décrivez l\'état de l\'actif, les défauts, rayures ou notes spéciales...',
  'characters': 'caractères',
  'empty': 'Vide',
  'added': 'Ajouté',
  'add_to_upload_queue': 'AJOUTER À LA FILE DE TÉLÉCHARGEMENT',
  'upload_queued': 'Téléchargement en file ! Vous pouvez continuer à scanner.',
  'failed_queue_upload': 'Échec de la mise en file du téléchargement',
  'scan_barcode_first': 'Veuillez scanner un code-barres avant de télécharger',
  'take_photo_first': 'Veuillez prendre au moins 1 photo avant de télécharger',
  'enter_barcode_and_photo': 'Veuillez entrer un code-barres et prendre au moins 1 photo',
  'uploading': 'Téléchargement',
  'n_uploads_in_queue': 'téléchargement(s) en file',
  'more_in_queue': 'de plus en file',
  'photos_saved_go_details': 'photo(s) enregistrée(s). Allez à l\'onglet Détails pour télécharger.',
  'upload_complete_opening_link': 'Téléchargement terminé ! Ouverture du lien...',
  'could_not_open_browser': 'Impossible d\'ouvrir le navigateur',
  'failed_open_link': 'Échec de l\'ouverture du lien',
  'failed_open_scanner': 'Échec de l\'ouverture du scanner. Réessayez.',
  'failed_open_camera': 'Échec de l\'ouverture de la caméra. Réessayez.',
  'delete_photo': 'Supprimer la Photo',
  'delete_photo_confirm': 'Êtes-vous sûr de vouloir supprimer cette photo ?',
  'upload_successful': 'Téléchargement Réussi !',
  'verify_data': 'Veuillez vérifier les données avant de soumettre à l\'entrepôt :',
  'barcode_number': 'Numéro de Code-barres',
  'photos_uploaded': 'Photos Téléchargées',
  'barcode_image': 'Image du Code-barres',
  'included': 'Incluse',
  'not_available': 'Non disponible',
  'no_description': 'Pas de description',
  'drive_folder': 'Dossier Google Drive :',
  'submit_to_warehouse': 'Soumettre à l\'Entrepôt',
  'opening_warehouse': 'Ouverture du formulaire d\'entrepôt...',
  'logout_confirm': 'Êtes-vous sûr de vouloir vous déconnecter ?',
  'photo_preview': 'Aperçu Photo',
  'upload_queue': 'File de Téléchargement',
  'active': 'active(s)',
  'completed': 'terminée(s)',
  'failed': 'échouée(s)',
  'clear_completed': 'Effacer les terminées',
  'no_uploads': 'Aucun téléchargement en file',
  'scanned_assets_appear': 'Les actifs scannés apparaîtront ici',
  'waiting': 'En Attente',
  'just_now': 'À l\'instant',
  'link_copied': 'Lien copié dans le presse-papiers',
  'remove_upload': 'Retirer le Téléchargement',
  'remove_upload_confirm': 'Retirer de la file ?',
  'copy_link': 'Copier le lien',
  'brand': 'Marque',
  'model': 'Modèle',
  'serial_number': 'Numéro de Série',
  'imei': 'IMEI',
  'storage': 'Stockage',
  'condition': 'État',
  'uploaded': 'téléchargée(s)',
  'photos_taken': 'Photos Prises',
  'device_scanned': 'Appareil Scanné',
  'info_verified': 'Info Vérifiée',
  'complete': 'Complet',
  'incomplete': 'Incomplet',
  'settings': 'Paramètres',
  'general': 'Général',
  'language': 'Langue',
  'select_language': 'Sélectionnez votre langue préférée',
  'preferences': 'Préférences',
  'theme': 'Thème',
  'customize_appearance': 'Personnaliser l\'apparence',
  'select_theme': 'Sélectionner le Thème',
  'notifications': 'Notifications',
  'receive_updates': 'Recevoir les notifications de téléchargement',
  'auto_upload': 'Téléchargement Auto',
  'auto_upload_subtitle': 'Télécharger automatiquement quand code-barres et photos sont prêts',
  'auto_sync': 'Synchroniser automatiquement les photos',
  'legal': 'Mentions Légales',
  'terms_of_service': 'Conditions d\'Utilisation',
  'privacy_policy': 'Politique de Confidentialité',
  'support': 'Support',
  'report_problem': 'Signaler un Problème',
  'rate_app': 'Noter l\'Application',
  'about': 'À Propos',
  'app_info': 'Info App',
  'version_info': 'Version et informations de l\'app',
  'app_description': 'Une app professionnelle d\'inspection qualité pour la documentation des actifs.',
  'dark': 'Sombre',
  'light': 'Clair',
  'system': 'Système',
  'google_drive': 'Google Drive',
  'connect_drive_desc': 'Connectez votre Google Drive pour stocker\net synchroniser vos photos en toute sécurité',
  'connect_to_drive': 'Connecter à Google Drive',
  'connecting': 'Connexion à Google Drive...',
  'connected': 'Connecté avec Succès !',
  'connection_failed': 'Connexion Échouée',
  'continue_to_app': 'Continuer vers l\'App',
  'retry': 'Réessayer la Connexion',
  'auth_expired': 'Authentification expirée. Veuillez vous reconnecter.',
  'scan_qr': 'Scanner les Codes QR',
  'scan_qr_desc': 'Scannez rapidement les codes QR avec votre caméra.',
  'scan_barcodes': 'Scanner les Codes-barres',
  'scan_barcodes_desc': 'Support de tous les formats principaux.',
  'save_export': 'Sauvegarder et Exporter',
  'save_export_desc': 'Sauvegardez vos scans et exportez-les vers Google Drive.',
  'skip': 'Passer',
  'next': 'Suivant',
  'get_started': 'Commencer',
  'welcome_title': 'Bienvenue sur\nInspector',
  'welcome_subtitle': 'Le moyen le plus rapide de scanner, inspecter et documenter\nvos actifs avec une qualité professionnelle',
  'quick_scanning': 'Scan rapide de codes-barres',
  'multi_angle_capture': 'Capture photo multi-angle',
  'secure_cloud_storage': 'Stockage cloud sécurisé',
  'instant_recognition': 'Reconnaissance\nInstantanée des Codes',
  'recognition_desc': 'Pointez votre caméra vers n\'importe quel code-barres et obtenez\ndes résultats instantanés. Supporte tous les formats principaux\ny compris EAN, UPC et codes QR',
  'scan_speed': 'Vitesse',
  'accuracy': 'Précision',
  'formats': 'Formats',
  'document_upload': 'Documentez et\nTéléchargez Instantanément',
  'document_upload_desc': 'Capturez plusieurs photos sous différents angles et\nsynchronisez automatiquement dans le cloud. Toutes les données\nsont chiffrées et sécurisées',
  'upload_5_photos': 'Téléchargez jusqu\'à 5 photos par actif',
  'auto_sync_cloud': 'Synchronisation auto dans le cloud',
  'encryption': 'Chiffrement de bout en bout',
  'swipe_continue': 'ou glissez pour continuer',
  'home': 'Accueil',
  'scan_history': 'Historique des Scans',
  'cloud_backup': 'Sauvegarde Cloud',
  'logout': 'Déconnexion',
  'Profile': 'Profil',
  'View your profile': 'Voir votre profil',
  'App preferences': 'Préférences de l\'app',
  'Get help': 'Obtenir de l\'aide',
  'company': 'Entreprise',
  'contact': 'Contact',
  'website': 'Site Web',
  'all_rights_reserved': 'Tous droits réservés.',
  'no_cameras': 'Aucune caméra disponible sur cet appareil',
  'camera_init_failed': 'Échec de l\'initialisation de la caméra. Réessayez.',
  'capture_failed': 'Échec de la capture photo. Réessayez.',
  'starting_camera': 'Démarrage de la caméra...',
  'camera_not_available': 'Caméra non disponible',
  'remaining_photos': 'photo(s) restante(s)',
  'max_photos_reached': 'Nombre maximum de photos atteint',
  'retry_button': 'Réessayer',

  // Widget-specific
  'camera': 'Caméra',
  'barcode_scanner': 'Scanner de Codes',
  'bcn_number': 'NUMÉRO BCN',
  'copy_bcn': 'Copier BCN',
  'barcode_captured': 'Code-barres Capturé',
  'scan_new_barcode': 'Scanner un Nouveau Code',
  'device_description': 'Description de l\'Appareil',
  'upload_to_drive': 'TÉLÉCHARGER VERS DRIVE',
};

// German translations
const Map<String, String> _germanTranslations = {
  'app_name': 'AssetCapture',
  'quality_inspection': 'Qualitätsprüfung',
  'loading': 'Laden...',
  'version': 'Version',
  'sign_in_with_google': 'Mit Google anmelden',
  'secure_auth': 'Sichere Authentifizierung mit Google',
  'signing_in': 'Anmeldung läuft...',
  'sign_in_cancelled': 'Anmeldung wurde abgebrochen oder ist fehlgeschlagen',
  'details': 'Details',
  'scanner': 'Scanner',
  'device_info': 'Geräteinformationen',
  'completion_status': 'Abschlussstatus',
  'photos': 'Fotos',
  'no_photos': 'Noch keine Fotos',
  'tap_to_add': 'Tippen Sie auf die Kamera-Taste, um Fotos hinzuzufügen',
  'add_photo': 'Foto Hinzufügen',
  'add_photos': 'Fotos Hinzufügen',
  'take_photo': 'Foto Aufnehmen',
  'choose_gallery': 'Aus Galerie Wählen',
  'cancel': 'Abbrechen',
  'close': 'Schließen',
  'delete': 'Löschen',
  'remove': 'Entfernen',
  'save': 'SPEICHERN',
  'view': 'Ansehen',
  'scanned': 'Gescannt',
  'start_scanning': 'Scan Starten',
  'scan_again': 'Erneut Scannen',
  'barcode_id': 'Barcode-ID',
  'not_scanned': 'Nicht gescannt',
  'barcode_copied': 'Barcode in Zwischenablage kopiert',
  'asset_description': 'Beschreibung des Vermögenswerts',
  'optional': 'Optional',
  'description': 'Beschreibung',
  'description_hint': 'Beschreiben Sie den Zustand, Mängel, Kratzer oder besondere Hinweise...',
  'characters': 'Zeichen',
  'empty': 'Leer',
  'added': 'Hinzugefügt',
  'add_to_upload_queue': 'ZUR UPLOAD-WARTESCHLANGE HINZUFÜGEN',
  'upload_queued': 'Upload in Warteschlange! Sie können weiter scannen.',
  'failed_queue_upload': 'Upload konnte nicht in die Warteschlange gestellt werden',
  'scan_barcode_first': 'Bitte zuerst einen Barcode scannen',
  'take_photo_first': 'Bitte mindestens 1 Foto aufnehmen',
  'enter_barcode_and_photo': 'Bitte Barcode eingeben und mindestens 1 Foto aufnehmen',
  'uploading': 'Wird hochgeladen',
  'n_uploads_in_queue': 'Upload(s) in Warteschlange',
  'more_in_queue': 'weitere in Warteschlange',
  'photos_saved_go_details': 'Foto(s) gespeichert. Gehen Sie zum Details-Tab zum Hochladen.',
  'upload_complete_opening_link': 'Upload abgeschlossen! Link wird geöffnet...',
  'could_not_open_browser': 'Browser konnte nicht geöffnet werden',
  'failed_open_link': 'Link konnte nicht geöffnet werden',
  'failed_open_scanner': 'Scanner konnte nicht geöffnet werden. Bitte erneut versuchen.',
  'failed_open_camera': 'Kamera konnte nicht geöffnet werden. Bitte erneut versuchen.',
  'delete_photo': 'Foto Löschen',
  'delete_photo_confirm': 'Sind Sie sicher, dass Sie dieses Foto löschen möchten?',
  'upload_successful': 'Upload Erfolgreich!',
  'verify_data': 'Bitte überprüfen Sie die Daten vor der Übermittlung an das Lager:',
  'barcode_number': 'Barcodenummer',
  'photos_uploaded': 'Fotos Hochgeladen',
  'barcode_image': 'Barcode-Bild',
  'included': 'Enthalten',
  'not_available': 'Nicht verfügbar',
  'no_description': 'Keine Beschreibung',
  'drive_folder': 'Google Drive Ordner:',
  'submit_to_warehouse': 'An Lager Senden',
  'opening_warehouse': 'Lagerformular wird geöffnet...',
  'logout_confirm': 'Sind Sie sicher, dass Sie sich abmelden möchten?',
  'photo_preview': 'Fotovorschau',
  'upload_queue': 'Upload-Warteschlange',
  'active': 'aktiv',
  'completed': 'abgeschlossen',
  'failed': 'fehlgeschlagen',
  'clear_completed': 'Abgeschlossene löschen',
  'no_uploads': 'Keine Uploads in der Warteschlange',
  'scanned_assets_appear': 'Gescannte Vermögenswerte erscheinen hier',
  'waiting': 'Wartend',
  'just_now': 'Gerade eben',
  'link_copied': 'Link in Zwischenablage kopiert',
  'remove_upload': 'Upload Entfernen',
  'remove_upload_confirm': 'Aus der Warteschlange entfernen?',
  'copy_link': 'Link kopieren',
  'brand': 'Marke',
  'model': 'Modell',
  'serial_number': 'Seriennummer',
  'imei': 'IMEI',
  'storage': 'Speicher',
  'condition': 'Zustand',
  'uploaded': 'hochgeladen',
  'photos_taken': 'Fotos Aufgenommen',
  'device_scanned': 'Gerät Gescannt',
  'info_verified': 'Info Verifiziert',
  'complete': 'Vollständig',
  'incomplete': 'Unvollständig',
  'settings': 'Einstellungen',
  'general': 'Allgemein',
  'language': 'Sprache',
  'select_language': 'Wählen Sie Ihre bevorzugte Sprache',
  'preferences': 'Präferenzen',
  'theme': 'Design',
  'customize_appearance': 'Erscheinungsbild anpassen',
  'select_theme': 'Design Auswählen',
  'notifications': 'Benachrichtigungen',
  'receive_updates': 'Upload-Statusbenachrichtigungen erhalten',
  'auto_upload': 'Auto-Upload',
  'auto_upload_subtitle': 'Automatisch hochladen wenn Barcode und Fotos bereit sind',
  'auto_sync': 'Fotos automatisch synchronisieren',
  'legal': 'Rechtliches',
  'terms_of_service': 'Nutzungsbedingungen',
  'privacy_policy': 'Datenschutzrichtlinie',
  'support': 'Support',
  'report_problem': 'Problem Melden',
  'rate_app': 'App Bewerten',
  'about': 'Über',
  'app_info': 'App-Info',
  'version_info': 'Version und App-Informationen',
  'app_description': 'Eine professionelle Qualitätsprüfungs-App für die Dokumentation von Vermögenswerten.',
  'dark': 'Dunkel',
  'light': 'Hell',
  'system': 'System',
  'google_drive': 'Google Drive',
  'connect_drive_desc': 'Verbinden Sie Ihr Google Drive, um Ihre\nFotos sicher zu speichern und zu synchronisieren',
  'connect_to_drive': 'Mit Google Drive Verbinden',
  'connecting': 'Verbindung zu Google Drive...',
  'connected': 'Erfolgreich Verbunden!',
  'connection_failed': 'Verbindung Fehlgeschlagen',
  'continue_to_app': 'Weiter zur App',
  'retry': 'Erneut Versuchen',
  'auth_expired': 'Authentifizierung abgelaufen. Bitte erneut anmelden.',
  'scan_qr': 'QR-Codes Scannen',
  'scan_qr_desc': 'Scannen Sie schnell QR-Codes mit Ihrer Kamera.',
  'scan_barcodes': 'Barcodes Scannen',
  'scan_barcodes_desc': 'Unterstützung aller gängigen Formate.',
  'save_export': 'Speichern & Exportieren',
  'save_export_desc': 'Speichern Sie Ihre Scans und exportieren Sie sie zu Google Drive.',
  'skip': 'Überspringen',
  'next': 'Weiter',
  'get_started': 'Los Geht\'s',
  'welcome_title': 'Willkommen bei\nInspector',
  'welcome_subtitle': 'Der schnellste Weg zum Scannen, Prüfen und Dokumentieren\nIhrer Vermögenswerte in professioneller Qualität',
  'quick_scanning': 'Schnelles Barcode-Scannen',
  'multi_angle_capture': 'Multi-Winkel-Fotoaufnahme',
  'secure_cloud_storage': 'Sichere Cloud-Speicherung',
  'instant_recognition': 'Sofortige\nBarcode-Erkennung',
  'recognition_desc': 'Richten Sie Ihre Kamera auf einen Barcode und erhalten Sie\nsofortige Ergebnisse. Unterstützt alle gängigen Formate\neinschließlich EAN, UPC und QR-Codes',
  'scan_speed': 'Geschwindigkeit',
  'accuracy': 'Genauigkeit',
  'formats': 'Formate',
  'document_upload': 'Dokumentieren &\nSofort Hochladen',
  'document_upload_desc': 'Erfassen Sie mehrere Fotos aus verschiedenen Winkeln und\nsynchronisieren Sie automatisch in die Cloud. Alle Daten\nsind verschlüsselt und sicher',
  'upload_5_photos': 'Bis zu 5 Fotos pro Vermögenswert',
  'auto_sync_cloud': 'Auto-Sync in die Cloud',
  'encryption': 'Ende-zu-Ende-Verschlüsselung',
  'swipe_continue': 'oder wischen zum Fortfahren',
  'home': 'Startseite',
  'scan_history': 'Scan-Verlauf',
  'cloud_backup': 'Cloud-Backup',
  'logout': 'Abmelden',
  'Profile': 'Profil',
  'View your profile': 'Profil anzeigen',
  'App preferences': 'App-Einstellungen',
  'Get help': 'Hilfe erhalten',
  'company': 'Unternehmen',
  'contact': 'Kontakt',
  'website': 'Webseite',
  'all_rights_reserved': 'Alle Rechte vorbehalten.',
  'no_cameras': 'Keine Kameras auf diesem Gerät verfügbar',
  'camera_init_failed': 'Kamera konnte nicht initialisiert werden. Bitte erneut versuchen.',
  'capture_failed': 'Fotoaufnahme fehlgeschlagen. Erneut versuchen.',
  'starting_camera': 'Kamera wird gestartet...',
  'camera_not_available': 'Kamera nicht verfügbar',
  'remaining_photos': 'Foto(s) übrig',
  'max_photos_reached': 'Maximale Anzahl Fotos erreicht',
  'retry_button': 'Erneut versuchen',

  // Widget-specific
  'camera': 'Kamera',
  'barcode_scanner': 'Barcode-Scanner',
  'bcn_number': 'BCN-NUMMER',
  'copy_bcn': 'BCN Kopieren',
  'barcode_captured': 'Barcode Erfasst',
  'scan_new_barcode': 'Neuen Barcode Scannen',
  'device_description': 'Gerätebeschreibung',
  'upload_to_drive': 'ZU DRIVE HOCHLADEN',
};

// Arabic translations
const Map<String, String> _arabicTranslations = {
  'app_name': 'AssetCapture',
  'quality_inspection': 'فحص الجودة',
  'loading': 'جاري التحميل...',
  'version': 'الإصدار',
  'sign_in_with_google': 'تسجيل الدخول بواسطة Google',
  'secure_auth': 'مصادقة آمنة مع Google',
  'signing_in': 'جاري تسجيل الدخول...',
  'sign_in_cancelled': 'تم إلغاء تسجيل الدخول أو فشل',
  'details': 'التفاصيل',
  'scanner': 'الماسح',
  'device_info': 'معلومات الجهاز',
  'completion_status': 'حالة الإكمال',
  'photos': 'الصور',
  'no_photos': 'لا توجد صور بعد',
  'tap_to_add': 'اضغط على زر الكاميرا لإضافة صور',
  'add_photo': 'إضافة صورة',
  'add_photos': 'إضافة صور',
  'take_photo': 'التقاط صورة',
  'choose_gallery': 'اختر من المعرض',
  'cancel': 'إلغاء',
  'close': 'إغلاق',
  'delete': 'حذف',
  'remove': 'إزالة',
  'save': 'حفظ',
  'view': 'عرض',
  'scanned': 'تم المسح',
  'start_scanning': 'بدء المسح',
  'scan_again': 'مسح مرة أخرى',
  'barcode_id': 'معرف الباركود',
  'not_scanned': 'لم يتم المسح',
  'barcode_copied': 'تم نسخ الباركود إلى الحافظة',
  'asset_description': 'وصف الأصل',
  'optional': 'اختياري',
  'description': 'الوصف',
  'description_hint': 'صف حالة الأصل، أي عيوب أو خدوش أو ملاحظات خاصة...',
  'characters': 'حرف',
  'empty': 'فارغ',
  'added': 'تمت الإضافة',
  'add_to_upload_queue': 'إضافة إلى قائمة الرفع',
  'upload_queued': 'تم وضع الرفع في القائمة! يمكنك متابعة المسح.',
  'failed_queue_upload': 'فشل في إضافة الرفع إلى القائمة',
  'scan_barcode_first': 'يرجى مسح باركود أولاً قبل الرفع',
  'take_photo_first': 'يرجى التقاط صورة واحدة على الأقل قبل الرفع',
  'enter_barcode_and_photo': 'يرجى إدخال باركود والتقاط صورة واحدة على الأقل',
  'uploading': 'جاري الرفع',
  'n_uploads_in_queue': 'رفع في القائمة',
  'more_in_queue': 'المزيد في القائمة',
  'photos_saved_go_details': 'تم حفظ الصور. اذهب إلى تبويب التفاصيل للرفع.',
  'upload_complete_opening_link': 'اكتمل الرفع! جاري فتح الرابط...',
  'could_not_open_browser': 'تعذر فتح المتصفح',
  'failed_open_link': 'فشل في فتح الرابط',
  'failed_open_scanner': 'فشل في فتح الماسح. يرجى المحاولة مرة أخرى.',
  'failed_open_camera': 'فشل في فتح الكاميرا. يرجى المحاولة مرة أخرى.',
  'delete_photo': 'حذف الصورة',
  'delete_photo_confirm': 'هل أنت متأكد من حذف هذه الصورة؟',
  'upload_successful': 'تم الرفع بنجاح!',
  'verify_data': 'يرجى التحقق من البيانات قبل الإرسال إلى المستودع:',
  'barcode_number': 'رقم الباركود',
  'photos_uploaded': 'الصور المرفوعة',
  'barcode_image': 'صورة الباركود',
  'included': 'مضمنة',
  'not_available': 'غير متوفر',
  'no_description': 'بدون وصف',
  'drive_folder': 'مجلد Google Drive:',
  'submit_to_warehouse': 'إرسال إلى المستودع',
  'opening_warehouse': 'جاري فتح نموذج المستودع...',
  'logout_confirm': 'هل أنت متأكد من تسجيل الخروج؟',
  'photo_preview': 'معاينة الصورة',
  'upload_queue': 'قائمة الرفع',
  'active': 'نشط',
  'completed': 'مكتمل',
  'failed': 'فشل',
  'clear_completed': 'مسح المكتملة',
  'no_uploads': 'لا توجد عمليات رفع في القائمة',
  'scanned_assets_appear': 'ستظهر الأصول الممسوحة هنا',
  'waiting': 'في الانتظار',
  'just_now': 'الآن',
  'link_copied': 'تم نسخ الرابط إلى الحافظة',
  'remove_upload': 'إزالة الرفع',
  'remove_upload_confirm': 'إزالة من القائمة؟',
  'copy_link': 'نسخ الرابط',
  'brand': 'العلامة التجارية',
  'model': 'الموديل',
  'serial_number': 'الرقم التسلسلي',
  'imei': 'IMEI',
  'storage': 'التخزين',
  'condition': 'الحالة',
  'uploaded': 'مرفوعة',
  'photos_taken': 'الصور الملتقطة',
  'device_scanned': 'تم مسح الجهاز',
  'info_verified': 'تم التحقق من المعلومات',
  'complete': 'مكتمل',
  'incomplete': 'غير مكتمل',
  'settings': 'الإعدادات',
  'general': 'عام',
  'language': 'اللغة',
  'select_language': 'اختر لغتك المفضلة',
  'preferences': 'التفضيلات',
  'theme': 'المظهر',
  'customize_appearance': 'تخصيص مظهر التطبيق',
  'select_theme': 'اختر المظهر',
  'notifications': 'الإشعارات',
  'receive_updates': 'استلام إشعارات حالة الرفع',
  'auto_upload': 'الرفع التلقائي',
  'auto_upload_subtitle': 'رفع تلقائي عندما يكون الباركود والصور جاهزة',
  'auto_sync': 'مزامنة الصور تلقائياً',
  'legal': 'قانوني',
  'terms_of_service': 'شروط الخدمة',
  'privacy_policy': 'سياسة الخصوصية',
  'support': 'الدعم',
  'report_problem': 'الإبلاغ عن مشكلة',
  'rate_app': 'تقييم التطبيق',
  'about': 'حول',
  'app_info': 'معلومات التطبيق',
  'version_info': 'الإصدار ومعلومات التطبيق',
  'app_description': 'تطبيق فحص جودة احترافي لتوثيق الأصول بكفاءة.',
  'dark': 'داكن',
  'light': 'فاتح',
  'system': 'النظام',
  'google_drive': 'Google Drive',
  'connect_drive_desc': 'اربط Google Drive الخاص بك\nلتخزين ومزامنة صورك بأمان',
  'connect_to_drive': 'الاتصال بـ Google Drive',
  'connecting': 'جاري الاتصال بـ Google Drive...',
  'connected': 'تم الاتصال بنجاح!',
  'connection_failed': 'فشل الاتصال',
  'continue_to_app': 'المتابعة إلى التطبيق',
  'retry': 'إعادة المحاولة',
  'auth_expired': 'انتهت صلاحية المصادقة. يرجى تسجيل الدخول مرة أخرى.',
  'scan_qr': 'مسح رموز QR',
  'scan_qr_desc': 'امسح رموز QR بسرعة بكاميرتك.',
  'scan_barcodes': 'مسح الباركود',
  'scan_barcodes_desc': 'دعم جميع التنسيقات الرئيسية.',
  'save_export': 'حفظ وتصدير',
  'save_export_desc': 'احفظ عمليات المسح وصدرها إلى Google Drive.',
  'skip': 'تخطي',
  'next': 'التالي',
  'get_started': 'ابدأ',
  'welcome_title': 'مرحباً بك في\nالمفتش',
  'welcome_subtitle': 'أسرع طريقة لمسح وفحص وتوثيق\nأصولك بجودة احترافية',
  'quick_scanning': 'مسح سريع للباركود',
  'multi_angle_capture': 'التقاط صور متعددة الزوايا',
  'secure_cloud_storage': 'تخزين سحابي آمن',
  'instant_recognition': 'التعرف الفوري\nعلى الباركود',
  'recognition_desc': 'وجّه كاميرتك نحو أي باركود واحصل على\nنتائج فورية. يدعم جميع التنسيقات الرئيسية\nبما في ذلك EAN و UPC ورموز QR',
  'scan_speed': 'السرعة',
  'accuracy': 'الدقة',
  'formats': 'التنسيقات',
  'document_upload': 'وثّق وارفع\nفي الحال',
  'document_upload_desc': 'التقط صوراً متعددة من زوايا مختلفة\nوزامنها تلقائياً في السحابة. جميع البيانات\nمشفرة وآمنة',
  'upload_5_photos': 'ارفع حتى 5 صور لكل أصل',
  'auto_sync_cloud': 'مزامنة تلقائية في السحابة',
  'encryption': 'تشفير من طرف إلى طرف',
  'swipe_continue': 'أو اسحب للمتابعة',
  'home': 'الرئيسية',
  'scan_history': 'سجل المسح',
  'cloud_backup': 'النسخ الاحتياطي السحابي',
  'logout': 'تسجيل الخروج',
  'Profile': 'الملف الشخصي',
  'View your profile': 'عرض ملفك الشخصي',
  'App preferences': 'إعدادات التطبيق',
  'Get help': 'الحصول على مساعدة',
  'company': 'الشركة',
  'contact': 'الاتصال',
  'website': 'الموقع الإلكتروني',
  'all_rights_reserved': 'جميع الحقوق محفوظة.',
  'no_cameras': 'لا توجد كاميرات متاحة على هذا الجهاز',
  'camera_init_failed': 'فشل في تهيئة الكاميرا. يرجى المحاولة مرة أخرى.',
  'capture_failed': 'فشل في التقاط الصورة. حاول مرة أخرى.',
  'starting_camera': 'جاري بدء الكاميرا...',
  'camera_not_available': 'الكاميرا غير متاحة',
  'remaining_photos': 'صورة متبقية',
  'max_photos_reached': 'تم الوصول للحد الأقصى من الصور',
  'retry_button': 'إعادة المحاولة',

  // Widget-specific
  'camera': 'الكاميرا',
  'barcode_scanner': 'ماسح الباركود',
  'bcn_number': 'رقم BCN',
  'copy_bcn': 'نسخ BCN',
  'barcode_captured': 'تم التقاط الباركود',
  'scan_new_barcode': 'مسح باركود جديد',
  'device_description': 'وصف الجهاز',
  'upload_to_drive': 'الرفع إلى DRIVE',
};

// Chinese translations
const Map<String, String> _chineseTranslations = {
  'app_name': 'AssetCapture',
  'quality_inspection': '质量检测',
  'loading': '加载中...',
  'version': '版本',
  'sign_in_with_google': '使用 Google 登录',
  'secure_auth': '使用 Google 安全认证',
  'signing_in': '登录中...',
  'sign_in_cancelled': '登录已取消或失败',
  'details': '详情',
  'scanner': '扫描器',
  'device_info': '设备信息',
  'completion_status': '完成状态',
  'photos': '照片',
  'no_photos': '暂无照片',
  'tap_to_add': '点击相机按钮添加照片',
  'add_photo': '添加照片',
  'add_photos': '添加照片',
  'take_photo': '拍照',
  'choose_gallery': '从相册选择',
  'cancel': '取消',
  'close': '关闭',
  'delete': '删除',
  'remove': '移除',
  'save': '保存',
  'view': '查看',
  'scanned': '已扫描',
  'start_scanning': '开始扫描',
  'scan_again': '重新扫描',
  'barcode_id': '条码ID',
  'not_scanned': '未扫描',
  'barcode_copied': '条码已复制到剪贴板',
  'asset_description': '资产描述',
  'optional': '可选',
  'description': '描述',
  'description_hint': '描述资产状况、缺陷、划痕或特殊备注...',
  'characters': '字符',
  'empty': '空',
  'added': '已添加',
  'add_to_upload_queue': '添加到上传队列',
  'upload_queued': '已加入上传队列！您可以继续扫描。',
  'failed_queue_upload': '加入上传队列失败',
  'scan_barcode_first': '请先扫描条码再上传',
  'take_photo_first': '请至少拍摄1张照片再上传',
  'enter_barcode_and_photo': '请输入条码并拍摄至少1张照片',
  'uploading': '上传中',
  'n_uploads_in_queue': '个上传在队列中',
  'more_in_queue': '个在队列中',
  'photos_saved_go_details': '张照片已保存。前往详情标签上传。',
  'upload_complete_opening_link': '上传完成！正在打开分享链接...',
  'could_not_open_browser': '无法打开浏览器',
  'failed_open_link': '无法打开链接',
  'failed_open_scanner': '无法打开扫描器，请重试。',
  'failed_open_camera': '无法打开相机，请重试。',
  'delete_photo': '删除照片',
  'delete_photo_confirm': '确定要删除这张照片吗？',
  'upload_successful': '上传成功！',
  'verify_data': '请在提交到仓库前验证以下数据：',
  'barcode_number': '条码编号',
  'photos_uploaded': '已上传照片',
  'barcode_image': '条码图片',
  'included': '已包含',
  'not_available': '不可用',
  'no_description': '无描述',
  'drive_folder': 'Google Drive 文件夹：',
  'submit_to_warehouse': '提交到仓库',
  'opening_warehouse': '正在打开仓库表单...',
  'logout_confirm': '确定要退出登录吗？',
  'photo_preview': '照片预览',
  'upload_queue': '上传队列',
  'active': '进行中',
  'completed': '已完成',
  'failed': '失败',
  'clear_completed': '清除已完成',
  'no_uploads': '队列中无上传任务',
  'scanned_assets_appear': '扫描的资产将显示在此处',
  'waiting': '等待中',
  'just_now': '刚刚',
  'link_copied': '链接已复制到剪贴板',
  'remove_upload': '移除上传',
  'remove_upload_confirm': '从队列中移除？',
  'copy_link': '复制链接',
  'brand': '品牌',
  'model': '型号',
  'serial_number': '序列号',
  'imei': 'IMEI',
  'storage': '存储',
  'condition': '状态',
  'uploaded': '已上传',
  'photos_taken': '已拍照片',
  'device_scanned': '设备已扫描',
  'info_verified': '信息已验证',
  'complete': '完成',
  'incomplete': '未完成',
  'settings': '设置',
  'general': '通用',
  'language': '语言',
  'select_language': '选择您的首选语言',
  'preferences': '偏好设置',
  'theme': '主题',
  'customize_appearance': '自定义应用外观',
  'select_theme': '选择主题',
  'notifications': '通知',
  'receive_updates': '接收上传状态通知',
  'auto_upload': '自动上传',
  'auto_upload_subtitle': '条码和照片就绪后自动加入上传队列',
  'auto_sync': '自动同步照片',
  'legal': '法律信息',
  'terms_of_service': '服务条款',
  'privacy_policy': '隐私政策',
  'support': '支持',
  'report_problem': '报告问题',
  'rate_app': '评价应用',
  'about': '关于',
  'app_info': '应用信息',
  'version_info': '版本和应用信息',
  'app_description': '专业的质量检测应用，用于简化资产文档记录。',
  'dark': '深色',
  'light': '浅色',
  'system': '跟随系统',
  'google_drive': 'Google Drive',
  'connect_drive_desc': '连接您的 Google Drive\n安全存储和同步您的照片',
  'connect_to_drive': '连接到 Google Drive',
  'connecting': '正在连接 Google Drive...',
  'connected': '连接成功！',
  'connection_failed': '连接失败',
  'continue_to_app': '继续使用应用',
  'retry': '重试连接',
  'auth_expired': '认证已过期，请重新登录。',
  'scan_qr': '扫描二维码',
  'scan_qr_desc': '使用相机快速扫描二维码。',
  'scan_barcodes': '扫描条形码',
  'scan_barcodes_desc': '支持所有主要条形码格式。',
  'save_export': '保存和导出',
  'save_export_desc': '保存扫描记录并导出到 Google Drive。',
  'skip': '跳过',
  'next': '下一步',
  'get_started': '开始使用',
  'welcome_title': '欢迎使用\n检测员',
  'welcome_subtitle': '扫描、检测和记录资产的\n最快捷专业方式',
  'quick_scanning': '快速条码扫描',
  'multi_angle_capture': '多角度照片拍摄',
  'secure_cloud_storage': '安全云存储',
  'instant_recognition': '即时条码\n识别',
  'recognition_desc': '将相机对准任何条码即可获得\n即时结果。支持所有主要格式\n包括 EAN、UPC 和 QR 码',
  'scan_speed': '扫描速度',
  'accuracy': '准确率',
  'formats': '格式',
  'document_upload': '即时记录\n并上传',
  'document_upload_desc': '从不同角度拍摄多张照片并\n自动同步到云端。所有数据\n均经过加密且安全',
  'upload_5_photos': '每个资产最多上传5张照片',
  'auto_sync_cloud': '自动同步到云存储',
  'encryption': '端到端加密',
  'swipe_continue': '或滑动继续',
  'home': '首页',
  'scan_history': '扫描历史',
  'cloud_backup': '云备份',
  'logout': '退出登录',
  'Profile': '个人资料',
  'View your profile': '查看您的个人资料',
  'App preferences': '应用偏好设置',
  'Get help': '获取帮助',
  'company': '公司',
  'contact': '联系方式',
  'website': '网站',
  'all_rights_reserved': '版权所有。',
  'no_cameras': '此设备没有可用的摄像头',
  'camera_init_failed': '摄像头初始化失败，请重试。',
  'capture_failed': '拍照失败，请重试。',
  'starting_camera': '正在启动摄像头...',
  'camera_not_available': '摄像头不可用',
  'remaining_photos': '张照片剩余',
  'max_photos_reached': '已达到最大照片数量',
  'retry_button': '重试',

  // Widget-specific
  'camera': '相机',
  'barcode_scanner': '条码扫描器',
  'bcn_number': 'BCN编号',
  'copy_bcn': '复制BCN',
  'barcode_captured': '条码已捕获',
  'scan_new_barcode': '扫描新条码',
  'device_description': '设备描述',
  'upload_to_drive': '上传到DRIVE',
};

/// Extension to easily access translations
extension TranslationExtension on BuildContext {
  String tr(String key) {
    try {
      return Provider.of<LanguageService>(this, listen: false).translate(key);
    } catch (e) {
      return key;
    }
  }
}
